### ISSUE TITLE
Client crash after accepting TPA

### ISSUE THREAD

**Issue by dandin87** [CodedSakura/FabricTPA#2] opened 2020-12-09 08:33 UTC
After accepting a TPA from another player the client crashes to desktop. All of Fabric 3 server.

[00:28:21] [main/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: net.minecraft.text.LiteralText cannot be cast to net.minecraft.text.TranslatableText
	at net.minecraft.client.gui.hud.BossBarHud.handler$bgl000$renderCustomBossBar(BossBarHud.java:532) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.client.gui.hud.BossBarHud.renderBossBar(BossBarHud.java) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.client.gui.hud.BossBarHud.render(BossBarHud.java:44) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:208) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:597) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1048) ~[intermediary-1.16.4.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:681) [intermediary-1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]

**Comment by CodedSakura** [comment] 2020-12-09 09:46
I managed to reproduce only once; If it happens every time for you, can you give more specifics, like client mods, client (fabric) versions, server Fabric API version and server mods?

**Comment by dandin87** [comment] 2020-12-09 16:58
https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/3133172 All of Fabric 3 v2.5.2 modpack. Minecraft 1.16.4. It happens every time to the person being teleported. Hoping to add it to the public servers since GunPowder has not been maintained.

**Comment by CodedSakura** [comment] 2020-12-10 18:40
Okay this is really puzzling me, `LiteralText` and `TranslatableText` should be basically interchangeable. It could be that one of the other 140+ mods changes some functionality of the `CommandBossBar`, but i really don't want to try to find out which one...

If i can't find the cause/a solution, would a temporary one be okay? I'm thinking a gamerule/connfig that allows to bypass the boss bar, and use some other method for the countdown.

**Comment by dandin87** [comment] 2020-12-10 21:54
I probably should have grabbed the crash log. forgot I also have useful things like mixintrace. Here is the crash log. https://hastebin.com/idojumulac.yaml and here is the list of BossBarHud Mixins. Much smaller lol. :) But yes a toggle for not using the boss bar would also work.
	Mixins in Stacktrace: 
		net.minecraft.class_337:
			draylar.battletowers.mixin.BossBarHudMixin (battletowers.mixins.json)
			com.github.chainmailstudios.astromine.mixin.BossBarHudMixin (astromine.mixins.json)

**Comment by CodedSakura** [comment] 2020-12-10 22:13
Thanks to the extra info you've given, I have found that the incompatible mod is Battle Towers, and I've submitted an issue regarding this (https://github.com/Draylar/battle-towers/issues/35).
Meanwhile I'll release update 1.3.0, adding a config and an option to disable the BossBar.

Leaving this issue open while https://github.com/Draylar/battle-towers/issues/35 is not solved.

**Comment by CodedSakura** [comment] 2020-12-10 23:51
Should be fixed on battle-towers side with v3.3.0
https://github.com/Draylar/battle-towers/issues/35#issuecomment-742871236

**Closed as completed by CodedSakura** 2020-12-10 23:51 UTC
Labels: bug

**Comment by dandin87** [comment] 2020-12-11 02:39
Just thought I would let you know, that Battle Towers was causing the same client crash after someone named a wither on AoF3 NA server causing anyone going into the End to crash as well haha.
